config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update] do
    resources :avatars, only: [:create]
  end
  resources :events do
    resources :participations
  end
  namespace :admin do
    root 'admin#index'
    resources :users
  end
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  # after_create :creator_congrats

  def creator_congrats
    UserMailer.new_participant(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances
  has_many :users, through: :attendances

  has_one_attached :cover

  validates :start_date, :duration, :title, :description, :price, :location, presence: true
  validates :duration, numericality: { only_integer: true, greater_than: 0 }
  validates :title, length: { in: 5..140 }
  validates :description, length: { in: 20..1000 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 1001 }
  validate :future_event
  validate :multiple_of_five

  def end_date
    # date de fin c'est la date de début + la durée en minutes
    self.start_date + (60 * self.duration)
  end

  def is_free?
    self.price == 0 ? true : false
  end

  private

  def future_event
    # on valide que la date de départ est bien dans le futur
    errors.add(:start_date, "must be in the future") unless
    self.start_date > Time.now
  end

  def multiple_of_five
    # on vérifie que la durée est bien multiple de 5
    errors.add(:duration, "must a multiple of 5") unless
    self.duration % 5 == 0    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances
  has_many :events

  has_one_attached :avatar

  # after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  def index
    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def update
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    # on vérifie s'il y a un paramètre avatar pour pas envoyer d'erreur si pas d'avatar
    if params[:avatar]
      @user.avatar.attach(params[:avatar])
    else
      flash[:alert] = "Pas de changement de photo de profil."     
    end
    redirect_to(user_path(@user))
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @creator = @event.user

    # if current_user == @creator
    # if @event.users.include?(current_user)
  end

  def new
  end

  def create
    @event = Event.new(title: params[:title], location: params[:location], start_date: params[:start_date], duration: params[:duration].to_i, description: params[:description], price: params[:price].to_i, user: current_user)
    if @event.save && params[:cover]
      @event.cover.attach(params[:cover])
      flash[:notice] = "Évènement créé."
      redirect_to event_path(@event.id)
    else
      flash[:alert] = "Erreur. Essaye encore."
      redirect_to new_event_path
    end
  end

  def edit
    @event = Event.find(params[:id])    
  end

  def update
    @event = Event.find(params[:id])
    if !params[:cover].nil?
      @event.cover.purge
      @event.cover.attach(params[:cover])    
    end
    if @event.update(title: params[:title], location: params[:location], start_date: params[:start_date], duration: params[:duration].to_i, description: params[:description], price: params[:price].to_i, user: current_user)
      flash[:notice] = "Ton évènement a bien été modifié."
      redirect_to event_path(params[:id])
    else
      flash[:alert] = "Ton évènement n'a pas pu être modifié."
      redirect_to edit_event_path(params[:id])
    end
  end

  def destroy
    @event = Event.find(params[:id])    
    if @event.destroy
      flash[:notice] = "Ton évènement a bien été supprimé."
      redirect_to root_path
    else
      flash[:alert] = "Problème. Ton évènement n'a pas pu être supprimé."
      redirect_to edit_event_path(params[:id])
    end
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @event = Event.find(params[:event_id])
    @participants = @event.users    
  end

  def new
    @event = Event.find(params[:event_id])
  end
  
  def create
    @event = Event.find(params[:event_id]) 
    
    if @event.is_free?
      Attendance.create(user: current_user, event: @event)
      flash[:notice] = "Inscription réussie. Bravo."
      redirect_to event_path(params[:event_id])
    else
      # Amount in cents
      @amount = @event.price.to_i * 100
    
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })
    
      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'eur',
      })

      if charge["paid"] == true
        #Save customer to the db
        Attendance.create(user: current_user, event: @event, stripe_customer_id: customer.id)
        flash[:notice] = "Paiement réussi. Bravo."
        redirect_to event_path(params[:event_id])
      end
    end

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_event_participation_path(params[:event_id])
        
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  
  before_action :authenticate_user! #, except: [:index]
  before_action :match_current_user #, except: [:index]

  # def index
  #   redirect_to root_path  
  # end

  def show
    @user = User.find(params[:id])
    @events = Event.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(first_name: params[:first_name], last_name: params[:last_name], description: params[:description])
    redirect_to @user
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def match_current_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      flash[:alert] = "Page non accessible."
      redirect_to root_path
    end
  end
end

app/views/admin/admin/index.html.erb
<h2>Bien le bonjour</h2>

app/views/admin/users/index.html.erb
<table>
  <tr>
    <th>Id</th>
    <th>Prénom</th>
    <th>Nom</th>
    <th>Email</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td>Edit</td>
      <td>Delete</td>
    </tr>
  <% end %>
</table>

app/views/events/edit.html.erb
<div class="headline">Édite ton évènement</div>

<div>
  <%= form_tag event_path(params[:id]), method: "put", multipart: true, class: "form-group" do %>

    <div class="form-group form-check">
      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @event.title, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Adresse' %>
      <%= text_field_tag 'location', @event.location, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Date et Heure' %>
      <div class="date-input">
        <%= datetime_field_tag 'start_date', @event.start_date.strftime("%Y-%m-%dT%H:%M"), class: "form-control form-date" %>
        <%#= time_field_tag 'start_time', nil, class: "form-control form-date" %>
      </div>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Durée (en minutes)' %>
      <%= text_field_tag 'duration', @event.duration, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Description' %>
      <%= text_area_tag 'description', @event.description, rows: 3, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Prix (en €)' %>
      <%= text_field_tag 'price', @event.price, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Photo de couverture' %>
      <%= file_field_tag :cover %>
    </div>

    <%= submit_tag "Modifier", class: "btn btn-primary" %>
    <button type="button" class="btn btn-secondary"><%= link_to 'Retour', :back %></button>
    <button type="button" class="btn btn-secondary"><a href="<%= event_path(params[:id]) %>" data-confirm="C'est ton dernier mot ?" data-method="DELETE">Supprimer</a></button>
    
  <% end %>
</div>

app/views/events/index.html.erb
<div class="background"></div>
<div class="headline"><span>Made for</span><br> those who do</div>

<div class="page-content">
  <div class="index-title">Popular in <span>Bordeaux</span></div>

  <div class="section">
    <div class="d-flex flex-wrap justify-content-between mx-auto">
      <% @events.each do |event| %>
        <div class="card" style="width: 18rem;">
          <% if event.cover.attached? %>
            <%= image_tag event.cover %>
          <% else %>
            <%= image_tag 'covers/cover' + rand(1..10).to_s + '.png', alt: "Couverture évènement", class: "card-img-top" %>            
          <% end %>
          <div class="card-body">
            <div class="card-date"><%= event.start_date.strftime("%a, %b %d") %></div>
            <h5 class="card-title"><%= link_to event.title, event_path(event.id) %></h5>
            <div class="card-location"><%= event.location %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="headline">Crée un évènement</div>

<div>
  <%= form_tag events_path, method: "post", multipart: true, class: "form-group" do %>

    <div class="form-group form-check">
      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', nil, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Adresse' %>
      <%= text_field_tag 'location', nil, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Date et Heure' %>
      <div class="date-input">
        <%= datetime_field_tag 'start_date', nil, class: "form-control form-date" %>
      </div>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Durée (en minutes)' %>
      <%= text_field_tag 'duration', nil, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Description' %>
      <%= text_area_tag 'description', nil, rows: 3, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Prix (en €)' %>
      <%= text_field_tag 'price', nil, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Photo de couverture' %>
      <%= file_field_tag :cover %>
    </div>

    <%= submit_tag "Publier", class: "btn btn-primary" %>
    <button type="button" class="btn btn-secondary"><%= link_to 'Retour', :back %></button>
    
  <% end %>
</div>

app/views/events/show.html.erb
<div class="event-main">
  <div class="head-img">
    <% if @event.cover.attached? %>
      <%= image_tag @event.cover, alt: 'Couverture' %>
    <% else %>
      Image
    <% end %>
  </div>
  <div class="head-infos">
    <div class="card-date"><%= @event.start_date.strftime("%a, %b %d") %></div>
    <h2><%= @event.title %></h2>
    <p>Par <%= @creator.first_name %> <%= @creator.last_name %></p>
    <p>
    <% if @event.is_free? %>
      Gratuit
    <% else %>
      <%= @event.price %> €    
    <% end %>
    </p>
    <p><%= @event.attendances.count %> personnes inscrites</p>
  </div>

  <div class="button-space">
    <button type="button" class="btn btn-inscription">
      <% if current_user == @creator %>
        <%= link_to "Mon espace évènement", event_participations_path(params[:id]) %>
      <% elsif @event.users.include?(current_user) %>
        <%= link_to "Déjà inscrit(e)", event_path(params[:id]) %>        
      <% else %>
        <% if @event.is_free? %>
          <%= link_to "S'inscrire", event_participations_path(params[:id]), method: 'post' %>
        <% else %>
          <%= link_to "S'inscrire", new_event_participation_path(params[:id]) %>                
        <% end %>
      <% end %>
    </button>
  </div>

  <div class="description">
    <h4>Description</h4>
    <%= @event.description %>
  </div>
  <div class="details-right-col">
    <div class="date">
      <h4>Date Et Heure</h4>
      Début le <%= @event.start_date.strftime("%d-%m-%Y à %H:%M") %><br>
      Fin le <%= @event.end_date.strftime("%d-%m-%Y à %H:%M") %>
    </div>
    <div class="location">
      <h4>Adresse</h4>
      <%= @event.location %>
    </div>
    <div class="refund">
      <h4>Politique De Remboursement</h4>
      Remboursements jusqu'à 1 jour avant l'événement.
      Les frais d'Eventbrite ne sont pas remboursables.
    </div>
  </div>

  <div class="creator-details">
    <span>Créé par</span>
    <div><%= @creator.first_name %> <%= @creator.last_name %></div>
    <div><%= @creator.description %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BdxEvent</title>
    <%= favicon_link_tag asset_path('https://cdn.evbstatic.com/s3-build/perm_001/8a4e23/django/images/favicons/favicon-32x32.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <%= link_to 'BdxEvent', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="header-right">
          <button class="header-element"><%= link_to 'Créer un évènement', new_event_path, class: "nav-item nav-link" %></button>
          <% if user_signed_in? %>
            <button class="header-element">
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, alt: 'Photo de profil' %>
              <% end %>
              <%= link_to 'Bonjour ' + current_user.first_name.to_s, user_path(current_user.id), class: "nav-item nav-link" %>
            </button>
            <button class="header-element"><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: "nav-item nav-link" %></button>
          <% else %>
            <button class="header-element"><%= link_to 'Se connecter', new_user_session_path, class: "nav-item nav-link" %></button>
            <button class="header-element"><%= link_to "S'inscrire", new_user_registration_path, class: "nav-item nav-link" %></button>
          <% end %>
        </div>
      </nav>
    </header>
    <div class="blank-space"></div>
    <div class="navbar-img"></div>

    <% if notice != nil || alert != nil %>
      <div class="flash"><%= notice %><%= alert %></div>      
    <% end %>

    <%= yield %>

    <footer>
      <div class="footer-logo">Bdx Event Project</div>
    </footer>
  </body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

app/views/participations/create.html.erb
<h2>Paiement de <strong><%= @event.price %>€</strong> réalisé avec succès.</h2>

app/views/participations/index.html.erb
<div class="headline">Page administrateur</div>
<div class="profile-page">
  <h2>Participants</h2>

  <table>
    <tr class="table-head">
      <th>Prénom</th>
      <th>Nom</th>
      <th>Email</th>
      <th>Description</th>
    </tr>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.first_name %></td>
        <td><%= participant.last_name %></td>
        <td><%= participant.email %></td>
        <td><%= participant.description %></td>
      </tr>
    <% end %>
  </table>

  <div class="d-flex justify-content-center">
    <button class="btn btn-secondary"><%= link_to "Éditer mon évènement", edit_event_path(params[:event_id]) %></button>
  </div>
</div>

app/views/participations/new.html.erb
<%= form_tag event_participations_path(params[:event_id]) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <div class="event-title"><%= @event.title %></div>
    <label class="amount">
      <span>Prix de l'évènement : <%= @event.price %>€</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Inscription à un évènement"
          data-amount="<%= @event.price.to_i * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/users/edit.html.erb
<div class="headline">Édite ton profil</div>

<div>
  <%= form_tag user_avatars_path(@user), multipart: true do %>
    <%= label_tag 'Photo de profil' %><br>
    <%= file_field_tag :avatar %>
    <%= submit_tag 'Mettre à jour', class: "btn btn-primary" %>
  <% end %>
</div>

<div>
  <%= form_tag user_path(@user.id), method: "patch", class: "form-group" do %>

    <div class="form-group form-check">
      <%= label_tag 'Prénom' %>
      <%= text_field_tag 'first_name', @user.first_name, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Nom' %>
      <%= text_field_tag 'last_name', @user.last_name, class: "form-control" %>
    </div>

    <div class="form-group form-check">
      <%= label_tag 'Description' %>
      <%= text_area_tag 'description', @user.description, rows: 3, class: "form-control" %>
    </div>

    <%= submit_tag "Modifier", class: "btn btn-primary" %>
    <button type="button" class="btn btn-secondary"><%= link_to 'Retour', :back %></button>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="headline">Ton profil</div>
<div class="profile-page">
  <h2>Mes informations</h2>

  <table>
    <tr>
      <th>Photo</th>
      <th>Prénom</th>
      <th>Nom</th>
      <th>Email</th>
      <th>Description</th>
    </tr>
    <tr>
      <td class="profile-pic">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, alt: 'Avatar' %>
        <% else %>
          <%= image_tag 'avatar-default.png', alt: 'Default Avatar' %>          
        <% end %>
      </td>
      <td><%= @user.first_name %></td>
      <td><%= @user.last_name %></td>
      <td><%= @user.email %></td>
      <td><%= @user.description %></td>
    </tr>
  </table>

  <div class="d-flex justify-content-center">
    <button class="btn btn-secondary" style="margin-right: 20px;"><%= link_to 'Modifier email ou mot de passe', edit_user_registration_path %></button>
    <button class="btn btn-secondary"><%= link_to 'Modifier mes informations', edit_user_path(@user.id) %></button>
  </div>

  <h2>Évènements créés</h2>
  <table>
    <tr>
      <th>Titre</th>
      <th>Date</th>
      <th>Participants</th>
      <th>Lien</th>
    </tr>
    <% @user.events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start_date.strftime("%d/%m/%Y à %Hh%M") %></td>
        <td class="column-center"><%= event.users.count %></td>
        <td><button class="btn btn-secondary"><%= link_to 'Voir', event_path(event.id) %></button></td>
      </tr>
    <% end %>
  </table>

  <h2>Évènements auxquels tu participes</h2>
  <table>
    <tr>
      <th>Titre</th>
      <th>Date</th>
      <th>Lien</th>
    </tr>
    <% @user.attendances.each do |attendance| %>
      <% event = @events.select{ |event| event.id == attendance.event_id }.reduce %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start_date.strftime("%d/%m/%Y à %Hh%M") %></td>
        <td><button class="btn btn-secondary"><%= link_to 'Voir', event_path(event.id) %></button></td>
      </tr>
    <% end %>
  </table>
</div>